### ISSUE TITLE
Push into pygobject for win32

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#22]
I don't know if these this will pick up new pycairo when upstream pygobject changes to this fork or not ?

https://sourceforge.net/projects/pygobjectwin32/files/

http://opensourcepack.blogspot.co.uk/p/pygobject-pygi-aio.html

This is almost a special case #20 as a weird kind of distro :)

**Comment by stuaxo** [comment]
Just noticed the update in the other ticket, will see if I can contact the pygi-aio author...

**Comment by lazka** [comment]
@tumagonx

**Comment by tumagonx** [comment]
oh new pycairo, awesome!
I could make new pygi-aio 3.24 but it will still stuck with gtk 3.18 to keep clutter-gtk related works.

**Comment by stuaxo** [comment]
Looks like Gtk 3.22 is the major last 3.x version of Gtk, but I guess if you are stuck on gtk 3.18 then keeping that as the number makes the most sense ?

If you manage to manage to make a build with the new of pygi-aio release of pycairo in it, I will definitely give it a test.

**Comment by lazka** [comment]
@tumagonx if you encounter any problems please report them. We have a mingw based test runner now, so that should prevent any regressions in that area.

Theoretically using pycairo 1.13 and pygobject 3.25/26 with gtk+ 3.18 shouldn't be a problem.

I guess there nothing more we can do here, so closing.
