### ISSUE TITLE
Provider a newer cairo in Windows wheels

### ISSUE THREAD

**Issue by lazka** [pygobject/pycairo#256]
Some work already done in #243

Ideally we'd pin down all transitive dependencies, like gst-build.

**Comment by naveen521kk** [comment]
> Some work already done in https://github.com/pygobject/pycairo/pull/243

I did so that we don't need to depend on the other one. That PR did work and built wheels locally but didn't pass the test suite. I remember all the tests with exception handling failed, dunno why, could be because of static build of Cairo. I'll post the test suite run output later today.

**Comment by naveen521kk** [comment]
> Ideally we'd pin down all transitive dependencies, like gst-build.

I thought meson subprojects should do the work for us right? Or am I wrong?

**Comment by lazka** [comment]
> I thought meson subprojects should do the work for us right? Or am I wrong?

cairo has various git dependencies: https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/subprojects/pixman.wrap As far as I understand this means it's not reproducible.

**Comment by naveen521kk** [comment]
> As far as I understand this means it's not reproducible.

Hmm, okay I see `master` branch being used there, which isn't reproducible. I'll add support for that in that PR. Or maybe rather than building ourselves manually we can create those subprojects files our ourselves with version we need, right?

The tests failing on static build did demotivate me from working on it and made that PR stale. Probably, need to investigate why it happens.

**Comment by lazka** [comment]
From what I understood we can create a dummy meson project and provide our own subproject with hardcoded versions. But that's all a stretch goal, so don't worry about it.

Another question is, if we build cairo in this repo, or create a separate repo which just provides the cairo build artefcats.

**Comment by naveen521kk** [comment]
> Another question is, if we build cairo in this repo, or create a separate repo which just provides the cairo build artifacts, similar to https://github.com/preshing/cairo-windows

Hmm, I think having a seperate repo would be better, but in the PR I made it so that it's included in the build process of pycairo itself. Which means, if Cairo or pkg-config isn't available while building pycairo, the build process will automatically build one(the aim was to make it buildable on all platforms, but I never tested it). I was inspired by how matplotlib builds freetype and other deps when not available.

Maybe, if we gonna have a seperate repo then we don't need to include the build scripts for Cairo inside of pycairo itself as done in that PR and just download those binaries as it is done currently.

**Comment by stuaxo** [comment]
I guess having cairo build artifacts upstream would be ideal, but I'm not sure where we would even start.

Having our own repo, seems the easiest way for now as it builds on knowledge we already have.

**Comment by danyeaw** [comment]
Great idea to provide wheels for Windows! Gvsbuild is now pip installable, and it can generate wheels with the `--py-wheel` option. It already avoids meson subprojects. It would be really straightforward to create a CI pipeline to upload the wheels. If you like the approach, I would be glad to help out.

**Comment by lazka** [comment]
@danyeaw thanks for the offer, but we have everything set up already in the repo and https://github.com/pygobject/cairo-win-build

**Comment by lazka** [comment]
This is fixed now with the 1.23.0 release
