### ISSUE TITLE
Work through fd.o bug list

### ISSUE THREAD

**Issue by lazka** [pygobject/pycairo#4]
There are 32 bugs open on fd.o: https://bugs.freedesktop.org/buglist.cgi?component=general&list_id=611898&product=pycairo&resolution=---

We should look through them and see which ones are still relevant and should be imported.

- [x] https://bugs.freedesktop.org/show_bug.cgi?id=22940 -> #5
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=37414
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=44336
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=44526
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=49024 -> unclear, current code looks OK to me
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=50134
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=50985 -> can't reproduce with msys2
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=50989
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=53046
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=57455
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=57493
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=58771 -> #7
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=58772
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=58773
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=59765
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=64521
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=76759
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=80399
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=80672
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=80688
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=84413
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=86286
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=88539
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=89091
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=89160
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=89161
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=89162 -> #8
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=91561
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=92253
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=92567
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=97421
- [x] https://bugs.freedesktop.org/show_bug.cgi?id=99855

**Comment by stuaxo** [comment]
I'm definitely +1 on https://bugs.freedesktop.org/show_bug.cgi?id=97421 which allows method chaining - although it changes the signature, I doubt anyone checks that the return value is None for lineto, moveto etc.

If it gets merged then it will need documentation, though I don't want to go back and ask for docs if it is not going to get merged.

**Comment by lazka** [comment]
I'm -0.5. method chaining is really uncommon, even in python. Returning an object of the same type suggests that the operation might not be inplace but create a copy as is the convention in the python stdlib.

**Comment by lazka** [comment]
btw. for any API additions we should first look at cairocffi and try to be compatible with its API.

I've made a quick diff of the exposed API: https://bpaste.net/show/7d647cf5b256

**Comment by lazka** [comment]
All fixed

**Comment by stuaxo** [comment]
Fantastic work :)  Great seeing all the new APIs exposed.

**Comment by dbeecham** [comment]
Regarding method chaining (author here),

In my experience, method chaining is very common in Javascript (with derivatives) (e.g. promises, jQuery, every functional library, ...), Haskell (duh), and Lisp-like languages (Scheme, Clojure, e.g. ->). I often see it in Scala too. I don't very often see it in Python, I'm not sure why, so maybe it's not very "pythonic".

Also, we're only returning a copy of the pointer to the object, not a complete copy. We're increasing the pointer links though (Py_INCREF), perhaps there is alias problems to be considered, but I don't know, feels minor to me (you'd have to do something like a = ctx.move_to(); b = SomeClass(a); ctx.line_to();... very wierd, and nonsense in current implementation).

The thing I like about these sorts of things (["fluent interface"](https://en.wikipedia.org/wiki/Fluent_interface) I guess it's called? It's not the name I heard at university, the practice to [return self](https://stackoverflow.com/questions/1345001/is-it-bad-practice-to-make-a-setter-return-this)) is that you're not forcing mutation, and you're not forcing notation. But _not_ returning self does force mutation as well as notation.

Regarding signature change, yes, that's true. As you say, since the methods always returned None no matter what, I'm not sure why someone would check that it does, but perhaps someone did. In other cases it's not going to matter; it's optional and only adds work to the garbage collector.

Not trying to convince anyone of this or the other; just fact-checking - it's your library and I'm happy to patch it myself if I want to. It's your library and I'm thankful for your work regardless!

**Comment by lazka** [comment]
> Regarding method chaining (author here),
>
> In my experience, method chaining is very common in Javascript (with derivatives) (e.g. promises, jQuery, every functional library, ...), Haskell (duh), and Lisp-like languages (Scheme, Clojure, e.g. ->). I often see it in Scala too. I don't very often see it in Python, I'm not sure why, so maybe it's not very "pythonic".

I assume it's partly due to this: https://mail.python.org/pipermail/python-dev/2003-October/038855.html

I guess because I never used the listed languages much I'm not that used to that interface and as a result don't miss it. But I can see how one would..

> Also, we're only returning a copy of the pointer to the object, not a complete copy. We're increasing the pointer links though (Py_INCREF), perhaps there is alias problems to be considered, but I don't know, feels minor to me (you'd have to do something like a = ctx.move_to(); b = SomeClass(a); ctx.line_to();... very wierd, and nonsense in current implementation).

That's what I was getting at above. It's kinda clear that it doesn't return a copy, but you have to still explain it in the docs because that pattern is uncommon in Python.

> The thing I like about these sorts of things ("fluent interface" I guess it's called? It's not the name I heard at university, the practice to return self) is that you're not forcing mutation, and you're not forcing notation. But not returning self does force mutation as well as notation.
>
> Regarding signature change, yes, that's true. As you say, since the methods always returned None no matter what, I'm not sure why someone would check that it does, but perhaps someone did. In other cases it's not going to matter; it's optional and only adds work to the garbage collector.

I don't think that would be a big problem in this case. I can't think of cases where the return value would be used and be it by accident (in gtk some things can be passed as callbacks where the None return value sometimes works as return value due to truthiness...)

> Not trying to convince anyone of this or the other; just fact-checking - it's your library and I'm happy to patch it myself if I want to. It's your library and I'm thankful for your work regardless!

Thanks for your input!
