### ISSUE TITLE
updating pygobject

### ISSUE THREAD

**Issue by blap** [pygobject/pycairo#85]
When updating pygobject via pip in LinuxMint ("sudo pip install -U pygobject" or "sudo -H pip install -U pygobject"), I get this error:

```
Collecting pygobject
  Using cached pygobject-3.27.0.tar.gz
Requirement already up-to-date: pycairo>=1.11.1 in /usr/local/lib/python2.7/dist-packages (from pygobject)
Installing collected packages: pygobject
  Found existing installation: pygobject 3.20.0
    DEPRECATION: Uninstalling a distutils installed project (pygobject) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling pygobject-3.20.0:
      Successfully uninstalled pygobject-3.20.0
  Running setup.py install for pygobject ... error
...
gi/pygi-foreign-cairo.c:28:21: fatal error: pycairo.h: Arquivo ou diretório não encontrado
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

How can I solve this?
"pip list" show pycairo (1.15.4) and pygobject (3.20.0)

**Comment by lazka** [comment]
Uh, I don't think messing with the dpkg managed packages through pip is a good idea. Always use a virtualenv or install into your user directory. You'll break your system..

In pygobject (which is on pypi since yesterday, and kinda experimental) we only look in the default location for pycairo atm, which I guess is the reason it fails. I'll see if I can find a better approach.

Is your pygobject 3.20 installed through apt?

**Comment by blap** [comment]
Yes, from apt
`sudo apt-get install python-gobject`

**Comment by lazka** [comment]
Thanks, I'll try to get this fixed in pygobject in the coming days.

**Comment by lazka** [comment]
The new pygobject on pypi should work better

**Comment by lazka** [comment]
@blap Can you maybe test that it works now? If you don't care that's ok too and I'll just close this.
